create table if not exists public.registration_cards (
    id bigint generated by default as identity primary key,
    client_code text not null,
    registration_card_number text not null,
    guest_id text not null,
    confirmation_number text,
    token text not null unique,
    public_url text not null,
    status text not null default 'Generated',
    created_at timestamptz not null default now(),
    generated_at timestamptz,
    sent_at timestamptz,
    opened_at timestamptz,
    completed_at timestamptz,
    guest jsonb not null default '{}'::jsonb,
    response jsonb not null default '{}'::jsonb,
    constraint uq_registration_cards_client_number
        unique (client_code, registration_card_number),
    constraint uq_registration_cards_client_guest
        unique (client_code, guest_id)
);

create index if not exists idx_registration_cards_token
    on public.registration_cards(token);

create index if not exists idx_registration_cards_client_created
    on public.registration_cards(client_code, created_at desc);

alter table public.registration_cards enable row level security;
