-- Guest folio transaction details imported from OPERA Reporting & Analytics.
-- The property column keeps this reporting dataset safe for multi-property use.
create table if not exists public.rpt_guest_folio_details (
    folio_detail_id bigint generated by default as identity primary key,
    property text not null,
    folio_type text,
    bill_no text not null,
    bill_generation_date date,
    bill_generation_date_char text,
    fiscal_bill_no text,
    status text,
    room text,
    display_name text,
    sumft_debit_per_bill_no numeric(14, 2),
    sumft_credit_per_bill_no numeric(14, 2),
    trx_no text,
    trx_code text,
    trx_date date,
    ft_debit numeric(14, 2),
    ft_credit numeric(14, 2),
    transaction_description text,
    source_file text,
    loaded_at timestamptz not null default now()
);

create index if not exists rpt_guest_folio_details_property_bill_idx
    on public.rpt_guest_folio_details (property, bill_no);
create index if not exists rpt_guest_folio_details_property_room_idx
    on public.rpt_guest_folio_details (property, room);
create index if not exists rpt_guest_folio_details_property_guest_idx
    on public.rpt_guest_folio_details (property, display_name);

create or replace view public.rpt_guest_folio_summary as
select
    property,
    bill_no,
    max(bill_generation_date) as bill_generation_date,
    max(status) as status,
    max(room) as room,
    max(display_name) as display_name,
    max(sumft_debit_per_bill_no) as total_debit,
    max(sumft_credit_per_bill_no) as total_credit,
    count(*) as transaction_count
from public.rpt_guest_folio_details
group by property, bill_no;
